services:
  - type: web
    name: mlflow-server
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    ports:
      - port: 5000
    healthCheckPath: /
    persistentDisk:
      mountPath: /app/artifacts
      sizeGb: 1