services:
  - type: web
    name: mon-app-streamlit
    env: python
    buildCommand: ""
    startCommand: streamlit run dashboards/streamlit_app.py --server.port=10000 --server.enableCORS=false
    plan: free